hex2names = {
    "#a8bb19": ["Acid Green"],
    "#7cb9e8": ["Aero"],
    "#c9ffe5": ["Aero Blue"],
    "#b284be": ["African Purple"],
    "#5d8aa8": ["Air Force Blue (RAF)", "Rackley"],
    "#00308f": ["Air Force Blue (USAF)"],
    "#72a0c1": ["Air Superiority Blue"],
    "#a32638": ["Alabama Crimson"],
    "#f0f8ff": ["Alice Blue"],
    "#e32636": ["Alizarin Crimson", "Rose Madder"],
    "#c46210": ["Alloy Orange"],
    "#efdecd": ["Almond"],
    "#9f2b68": ["Amaranth"],
    "#f19cbb": ["Amaranth Pink"],
    "#ab274f": ["Amaranth Purple"],
    "#3b7a57": ["Amazon"],
    "#ffbf00": ["Amber", "Fluorescent Orange"],
    "#ff7e00": ["Amber (SAE/ECE)", "SAE/ECE Amber (Color)"],
    "#ff033e": ["American Rose"],
    "#9966cc": ["Amethyst"],
    "#a4c639": ["Android Green"],
    "#f2f3f4": ["Anti-flash White"],
    "#cd9575": ["Antique Brass"],
    "#665d1e": ["Antique Bronze"],
    "#915c83": ["Antique Fuchsia"],
    "#841b2d": ["Antique Ruby"],
    "#faebd7": ["Antique White", "Moccasin"],
    "#008000": ["Ao", "Green (HTML/CSS Color)", "Office Green"],
    "#8db600": ["Apple Green"],
    "#fbceb1": ["Apricot"],
    "#00ffff": ["Aqua", "Cyan", "Electric Cyan", "Spanish Sky Blue"],
    "#7fffd4": ["Aquamarine"],
    "#4b5320": ["Army Green"],
    "#3b444b": ["Arsenic"],
    "#8f9779": ["Artichoke"],
    "#e9d66b": ["Arylide Yellow", "Hansa Yellow"],
    "#b2beb5": ["Ash Grey"],
    "#87a96b": ["Asparagus"],
    "#ff9966": ["Atomic Tangerine", "Pink-orange"],
    "#a52a2a": ["Auburn", "Brown (web)", "Red-brown"],
    "#fdee00": ["Aureolin"],
    "#6e7f80": ["AuroMetalSaurus"],
    "#568203": ["Avocado"],
    "#007fff": ["Azure"],
    "#f0ffff": ["Azure Mist/web"],
    "#2e5894": ["B'dazzled Blue"],
    "#89cff0": ["Baby Blue"],
    "#a1caf1": ["Baby Blue Eyes"],
    "#f4c2c2": ["Baby Pink", "Tea Rose"],
    "#fefefa": ["Baby Powder"],
    "#ff91af": ["Baker-Miller Pink", "Schauss Pink"],
    "#21abcd": ["Ball Blue"],
    "#fae7b5": ["Banana Mania"],
    "#ffe135": ["Banana Yellow"],
    "#006a4e": ["Bangladesh Green", "Bottle Green"],
    "#e0218a": ["Barbie Pink"],
    "#7c0a02": ["Barn Red"],
    "#848482": ["Battleship Grey", "Old Silver"],
    "#98777b": ["Bazaar"],
    "#bcd4e6": ["Beau Blue", "Pale Aqua"],
    "#9f8170": ["Beaver"],
    "#f5f5dc": ["Beige"],
    "#9c2542": ["Big Dip O'ruby"],
    "#ffe4c4": ["Bisque"],
    "#3d2b1f": ["Bistre"],
    "#967117": ["Bistre Brown", "Drab", "Mode Beige", "Sand Dune", "Sandy Taupe"],
    "#cae00d": ["Bitter Lemon"],
    "#648c11": ["Bitter Lime"],
    "#fe6f5e": ["Bittersweet"],
    "#bf4f51": ["Bittersweet Shimmer"],
    "#000000": ["Black"],
    "#3d0c02": ["Black Bean"],
    "#253529": ["Black Leather Jacket"],
    "#3b3c36": ["Black Olive"],
    "#ffebcd": ["Blanched Almond"],
    "#a57164": ["Blast-off Bronze"],
    "#318ce7": ["Bleu De France"],
    "#ace5ee": ["Blizzard Blue"],
    "#faf0be": ["Blond"],
    "#0000ff": ["Blue"],
    "#1f75fe": ["Blue (Crayola)"],
    "#0093af": ["Blue (Munsell)"],
    "#0087bd": ["Blue (NCS)"],
    "#0247fe": ["Blue (RYB)"],
    "#333399": ["Blue (pigment)"],
    "#a2a2d0": ["Blue Bell"],
    "#126180": ["Blue Sapphire"],
    "#5072a7": ["Blue Yonder"],
    "#6699cc": ["Blue-gray", "Livid"],
    "#0d98ba": ["Blue-green"],
    "#8a2be2": ["Blue-violet"],
    "#4f86f7": ["Blueberry"],
    "#1c1cf0": ["Bluebonnet"],
    "#de5d83": ["Blush"],
    "#79443b": ["Bole", "Medium Tuscan Red"],
    "#0095b6": ["Bondi Blue"],
    "#e3dac9": ["Bone"],
    "#cc0000": ["Boston University Red"],
    "#006a4e": ["Bangladesh Green", "Bottle Green"],
    "#873260": ["Boysenberry"],
    "#0070ff": ["Brandeis Blue"],
    "#b5a642": ["Brass"],
    "#cb4154": ["Brick Red"],
    "#1dacd6": ["Bright Cerulean"],
    "#66ff00": ["Bright Green"],
    "#bf94e4": ["Bright Lavender"],
    "#d891ef": ["Bright Lilac"],
    "#c32148": ["Bright Maroon", "Maroon (Crayola)"],
    "#1974d2": ["Bright Navy Blue"],
    "#ff007f": ["Bright Pink", "Rose"],
    "#08e8de": ["Bright Turquoise"],
    "#d19fe8": ["Bright Ube"],
    "#f4bbff": ["Brilliant Lavender", "Electric Lavender"],
    "#ff55a3": ["Brilliant Rose", "Magenta (Crayola)"],
    "#fb607f": ["Brink Pink"],
    "#004225": ["British Racing Green"],
    "#122e18": ["British Racing Green II Metalic"],
    "#cd7f32": ["Bronze"],
    "#737000": ["Bronze Yellow"],
    "#964b00": ["Brown"],
    "#a52a2a": ["Auburn", "Brown (web)", "Red-brown"],
    "#6b4423": ["Brown-Nose", "Flattery"],
    "#1b4d3e": ["Brunswick Green", "English Green"],
    "#ffc1cc": ["Bubble Gum"],
    "#e7feff": ["Bubbles"],
    "#7bb661": ["Bud Green"],
    "#f0dc82": ["Buff"],
    "#480607": ["Bulgarian Rose"],
    "#800020": ["Burgundy"],
    "#deb887": ["Burlywood"],
    "#cc5500": ["Burnt Orange"],
    "#e97451": ["Burnt Sienna", "Light Red Ochre"],
    "#8a3324": ["Burnt Umber"],
    "#bd33a4": ["Byzantine"],
    "#702963": ["Byzantium"],
    "#007aa5": ["CG Blue"],
    "#e03c31": ["CG Red"],
    "#536872": ["Cadet"],
    "#5f9ea0": ["Cadet Blue"],
    "#91a3b0": ["Cadet Grey"],
    "#006b3c": ["Cadmium Green"],
    "#ed872d": ["Cadmium Orange"],
    "#e30022": ["Cadmium Red"],
    "#fff600": ["Cadmium Yellow"],
    "#a67b5b": ["Café Au Lait", "French Beige", "Tuscan Tan"],
    "#4b3621": ["Café Noir"],
    "#1e4d2b": ["Cal Poly Green"],
    "#a3c1ad": ["Cambridge Blue"],
    "#c19a6b": ["Camel", "Desert", "Fallow", "Lion", "Wood Brown"],
    "#efbbcc": ["Cameo Pink"],
    "#78866b": ["Camouflage Green"],
    "#ffef00": ["Canary Yellow", "Yellow (process)"],
    "#ff0800": ["Candy Apple Red"],
    "#e4717a": ["Candy Pink", "Tango Pink"],
    "#00bfff": ["Capri", "Deep Sky Blue"],
    "#592720": ["Caput Mortuum"],
    "#c41e3a": ["Cardinal"],
    "#00cc99": ["Caribbean Green"],
    "#960018": ["Carmine"],
    "#d70040": ["Carmine (M&P)", "Rich Carmine"],
    "#eb4c42": ["Carmine Pink"],
    "#ff0038": ["Carmine Red"],
    "#ffa6c9": ["Carnation Pink"],
    "#b31b1b": ["Carnelian", "Cornell Red"],
    "#99badd": ["Carolina Blue"],
    "#ed9121": ["Carrot Orange"],
    "#00563f": ["Castleton Green", "Sacramento State Green"],
    "#062a78": ["Catalina Blue"],
    "#703642": ["Catawba"],
    "#c95a49": ["Cedar Chest"],
    "#92a1cf": ["Ceil"],
    "#ace1af": ["Celadon"],
    "#007ba7": ["Celadon Blue", "Cerulean"],
    "#2f847c": ["Celadon Green"],
    "#b2ffff": ["Celeste", "Italian Sky Blue"],
    "#4997d0": ["Celestial Blue"],
    "#de3163": ["Cerise", "Cherry"],
    "#ec3b83": ["Cerise Pink"],
    "#007ba7": ["Celadon Blue", "Cerulean"],
    "#2a52be": ["Cerulean Blue"],
    "#6d9bc3": ["Cerulean Frost"],
    "#a0785a": ["Chamoisee"],
    "#f7e7ce": ["Champagne"],
    "#36454f": ["Charcoal"],
    "#232b2b": ["Charleston Green"],
    "#e68fac": ["Charm Pink", "Light Thulian Pink"],
    "#dfff00": ["Chartreuse"],
    "#7fff00": ["Chartreuse (web)"],
    "#de3163": ["Cerise", "Cherry"],
    "#ffb7c5": ["Cherry Blossom Pink"],
    "#cd5c5c": ["Chestnut", "Indian Red"],
    "#de6fa1": ["China Pink", "Liseran Purple", "Thulian Pink"],
    "#a8516e": ["China Rose"],
    "#aa381e": ["Chinese Red"],
    "#856088": ["Chinese Violet"],
    "#7b3f00": ["Chocolate"],
    "#d2691e": ["Chocolate (web)", "Cinnamon", "Cocoa Brown"],
    "#ffa700": ["Chrome Yellow"],
    "#98817b": ["Cinereous"],
    "#e34234": ["Cinnabar", "Vermilion"],
    "#d2691e": ["Chocolate (web)", "Cinnamon", "Cocoa Brown"],
    "#e4d00a": ["Citrine"],
    "#9fa91f": ["Citron"],
    "#7f1734": ["Claret"],
    "#fbcce7": ["Classic Rose"],
    "#0047ab": ["Cobalt"],
    "#fe001a": ["Coca-cola Red"],
    "#d2691e": ["Chocolate (web)", "Cinnamon", "Cocoa Brown"],
    "#965a3e": ["Coconut"],
    "#6f4e37": ["Coffee", "Tuscan Brown"],
    "#9bddff": ["Columbia Blue"],
    "#f88379": ["Congo Pink", "Coral Pink", "Tea Rose (orange)"],
    "#002e63": ["Cool Black"],
    "#8c92ac": ["Cool Grey", "Gray-Blue"],
    "#b87333": ["Copper"],
    "#da8a67": ["Copper (Crayola)", "Pale Copper"],
    "#ad6f69": ["Copper Penny"],
    "#cb6d51": ["Copper Red"],
    "#996666": ["Copper Rose"],
    "#ff3800": ["Coquelicot"],
    "#ff7f50": ["Coral"],
    "#f88379": ["Congo Pink", "Coral Pink", "Tea Rose (orange)"],
    "#ff4040": ["Coral Red"],
    "#893f45": ["Cordovan"],
    "#fbec5d": ["Corn", "Maize"],
    "#b31b1b": ["Carnelian", "Cornell Red"],
    "#6495ed": ["Cornflower Blue"],
    "#fff8dc": ["Cornsilk"],
    "#fff8e7": ["Cosmic Latte"],
    "#ffbcd9": ["Cotton Candy"],
    "#fffdd0": ["Cream"],
    "#dc143c": ["Crimson"],
    "#be0032": ["Crimson Glory"],
    "#00ffff": ["Aqua", "Cyan", "Electric Cyan", "Spanish Sky Blue"],
    "#00b7eb": ["Cyan (process)"],
    "#58427c": ["Cyber Grape"],
    "#ffd300": ["Cyber Yellow", "Yellow (NCS)"],
    "#ffff31": ["Daffodil"],
    "#f0e130": ["Dandelion"],
    "#00008b": ["Dark Blue"],
    "#666699": ["Dark Blue-Gray"],
    "#654321": ["Dark Brown", "Otter Brown"],
    "#5d3954": ["Dark Byzantium"],
    "#a40000": ["Dark Candy Apple Red"],
    "#08457e": ["Dark Cerulean"],
    "#986960": ["Dark Chestnut"],
    "#cd5b45": ["Dark Coral"],
    "#008b8b": ["Dark Cyan"],
    "#536878": ["Dark Electric Blue", "Payne's Grey"],
    "#b8860b": ["Dark Goldenrod"],
    "#a9a9a9": ["Dark Gray"],
    "#013220": ["Dark Green"],
    "#00416a": ["Dark Imperial Blue", "Indigo (dye)"],
    "#1a2421": ["Dark Jungle Green"],
    "#bdb76b": ["Dark Khaki"],
    "#483c32": ["Dark Lava", "Dark Taupe", "Taupe"],
    "#734f96": ["Dark Lavender"],
    "#534b4f": ["Dark Liver", "Liver"],
    "#543d37": ["Dark Liver (Horses)"],
    "#8b008b": ["Dark Magenta"],
    "#003366": ["Dark Midnight Blue"],
    "#4a5d23": ["Dark Moss Green"],
    "#556b2f": ["Dark Olive Green"],
    "#ff8c00": ["Dark Orange"],
    "#9932cc": ["Dark Orchid"],
    "#779ecb": ["Dark Pastel Blue"],
    "#03c03c": ["Dark Pastel Green"],
    "#966fd6": ["Dark Pastel Purple"],
    "#c23b22": ["Dark Pastel Red"],
    "#e75480": ["Dark Pink"],
    "#003399": ["Dark Powder Blue", "Smalt"],
    "#4f3a3c": ["Dark Puce"],
    "#872657": ["Dark Raspberry"],
    "#8b0000": ["Dark Red"],
    "#e9967a": ["Dark Salmon"],
    "#560319": ["Dark Scarlet"],
    "#8fbc8f": ["Dark Sea Green"],
    "#3c1414": ["Dark Sienna"],
    "#8cbed6": ["Dark Sky Blue"],
    "#483d8b": ["Dark Slate Blue"],
    "#2f4f4f": ["Dark Slate Gray"],
    "#177245": ["Dark Spring Green"],
    "#918151": ["Dark Tan"],
    "#ffa812": ["Dark Tangerine"],
    "#483c32": ["Dark Lava", "Dark Taupe", "Taupe"],
    "#cc4e5c": ["Dark Terra Cotta"],
    "#00ced1": ["Dark Turquoise"],
    "#d1bea8": ["Dark Vanilla"],
    "#9400d3": ["Dark Violet"],
    "#9b870c": ["Dark Yellow"],
    "#00703c": ["Dartmouth Green"],
    "#555555": ["Davy's Grey"],
    "#d70a53": ["Debian Red"],
    "#a9203e": ["Deep Carmine"],
    "#ef3038": ["Deep Carmine Pink"],
    "#e9692c": ["Deep Carrot Orange"],
    "#da3287": ["Deep Cerise"],
    "#fad6a5": ["Deep Champagne", "Sunset", "Tuscan"],
    "#b94e48": ["Deep Chestnut"],
    "#704241": ["Deep Coffee", "Roast Coffee"],
    "#c154c1": ["Deep Fuchsia", "Fuchsia (Crayola)"],
    "#004b49": ["Deep Jungle Green"],
    "#f5c71a": ["Deep Lemon"],
    "#9955bb": ["Deep Lilac"],
    "#cc00cc": ["Deep Magenta"],
    "#d473d4": ["Deep Mauve", "French Mauve"],
    "#355e3b": ["Deep Moss Green", "Hunter Green"],
    "#ffcba4": ["Deep Peach", "Peach (Crayola)"],
    "#ff1493": ["Deep Pink", "Fluorescent Pink"],
    "#a95c68": ["Deep Puce"],
    "#843f5b": ["Deep Ruby"],
    "#ff9933": ["Deep Saffron"],
    "#00bfff": ["Capri", "Deep Sky Blue"],
    "#4a646c": ["Deep Space Sparkle"],
    "#7e5e60": ["Deep Taupe"],
    "#66424d": ["Deep Tuscan Red"],
    "#ba8759": ["Deer"],
    "#1560bd": ["Denim"],
    "#c19a6b": ["Camel", "Desert", "Fallow", "Lion", "Wood Brown"],
    "#edc9af": ["Desert Sand"],
    "#ea3c53": ["Desire"],
    "#b9f2ff": ["Diamond"],
    "#696969": ["Dim Gray"],
    "#9b7653": ["Dirt"],
    "#1e90ff": ["Dodger Blue"],
    "#d71868": ["Dogwood Rose"],
    "#85bb65": ["Dollar Bill"],
    "#664c28": ["Donkey Brown"],
    "#967117": ["Bistre Brown", "Drab", "Mode Beige", "Sand Dune", "Sandy Taupe"],
    "#00009c": ["Duke Blue"],
    "#e5ccc9": ["Dust Storm"],
    "#efdfbb": ["Dutch White"],
    "#004953": ["Eagle Green", "Midnight Green"],
    "#e1a95f": ["Earth Yellow"],
    "#555d50": ["Ebony"],
    "#c2b280": ["Ecru", "Sand"],
    "#1b1b1b": ["Eerie Black"],
    "#614051": ["Eggplant"],
    "#f0ead6": ["Eggshell"],
    "#1034a6": ["Egyptian Blue"],
    "#7df9ff": ["Electric Blue"],
    "#ff003f": ["Electric Crimson"],
    "#00ffff": ["Aqua", "Cyan", "Electric Cyan", "Spanish Sky Blue"],
    "#00ff00": ["Electric Green", "Green", "Lime (web)"],
    "#6f00ff": ["Electric Indigo", "Indigo"],
    "#f4bbff": ["Brilliant Lavender", "Electric Lavender"],
    "#ccff00": ["Electric Lime", "Fluorescent Yellow", "French Lime"],
    "#bf00ff": ["Electric Purple"],
    "#3f00ff": ["Electric Ultramarine"],
    "#8f00ff": ["Electric Violet", "Violet"],
    "#ffff00": ["Electric Yellow", "Yellow"],
    "#50c878": ["Emerald", "Paris Green"],
    "#6c3082": ["Eminence"],
    "#1b4d3e": ["Brunswick Green", "English Green"],
    "#b48395": ["English Lavender"],
    "#ab4b52": ["English Red"],
    "#563c5c": ["English Violet", "Old Heliotrope"],
    "#96c8a2": ["Eton Blue"],
    "#44d7a8": ["Eucalyptus"],
    "#3b5998": ["Facebook Blue"],
    "#c19a6b": ["Camel", "Desert", "Fallow", "Lion", "Wood Brown"],
    "#801818": ["Falu Red"],
    "#b53389": ["Fandango"],
    "#de5285": ["Fandango Pink"],
    "#f400a1": ["Fashion Fuchsia", "Hollywood Cerise"],
    "#e5aa70": ["Fawn"],
    "#4d5d53": ["Feldgrau"],
    "#fdd5b1": ["Feldspar", "Light Apricot"],
    "#4f7942": ["Fern Green"],
    "#ff2800": ["Ferrari Red"],
    "#6c541e": ["Field Drab"],
    "#ce2029": ["Fire Engine Red"],
    "#b22222": ["Firebrick"],
    "#e25822": ["Flame"],
    "#fc8eac": ["Flamingo Pink"],
    "#6b4423": ["Brown-Nose", "Flattery"],
    "#f7e98e": ["Flavescent"],
    "#eedc82": ["Flax"],
    "#a2006d": ["Flirt"],
    "#fffaf0": ["Floral White"],
    "#ffbf00": ["Amber", "Fluorescent Orange"],
    "#ff1493": ["Deep Pink", "Fluorescent Pink"],
    "#ccff00": ["Electric Lime", "Fluorescent Yellow", "French Lime"],
    "#ff004f": ["Folly"],
    "#014421": ["Forest Green", "UP Forest Green"],
    "#228b22": ["Forest Green (web)"],
    "#a67b5b": ["Café Au Lait", "French Beige", "Tuscan Tan"],
    "#856d4d": ["French Bistre"],
    "#0072bb": ["French Blue"],
    "#fd3f92": ["French Fuchsia"],
    "#86608e": ["French Lilac", "Pomp And Power"],
    "#ccff00": ["Electric Lime", "Fluorescent Yellow", "French Lime"],
    "#d473d4": ["Deep Mauve", "French Mauve"],
    "#fd6c9e": ["French Pink"],
    "#4e1609": ["French Puce"],
    "#c72c48": ["French Raspberry"],
    "#f64a8a": ["French Rose"],
    "#77b5fe": ["French Sky Blue"],
    "#8806ce": ["French Violet"],
    "#ac1e44": ["French Wine"],
    "#a6e7ff": ["Fresh Air"],
    "#ff00ff": ["Fuchsia", "Magenta"],
    "#c154c1": ["Deep Fuchsia", "Fuchsia (Crayola)"],
    "#ff77ff": ["Fuchsia Pink"],
    "#cc397b": ["Fuchsia Purple"],
    "#c74375": ["Fuchsia Rose"],
    "#e48400": ["Fulvous"],
    "#cc6666": ["Fuzzy Wuzzy"],
    "#00ab66": ["GO Green"],
    "#3369e8": ["Google blue"],
    "#d50f25": ["Google red"],
    "#eeb211": ["Google yellow"],
    "#009925": ["Google green"],
    "#dcdcdc": ["Gainsboro"],
    "#e49b0f": ["Gamboge"],
    "#007f66": ["Generic Viridian"],
    "#f8f8ff": ["Ghost White"],
    "#fe5a1d": ["Giants Orange"],
    "#b06500": ["Ginger"],
    "#6082b6": ["Glaucous"],
    "#e6e8fa": ["Glitter"],
    "#d4af37": ["Gold"],
    "#ffd700": ["Gold (web) (Golden)"],
    "#85754e": ["Gold Fusion"],
    "#996515": ["Golden Brown"],
    "#fcc200": ["Golden Poppy"],
    "#ffdf00": ["Golden Yellow"],
    "#daa520": ["Goldenrod"],
    "#a8e4a0": ["Granny Smith Apple"],
    "#6f2da8": ["Grape"],
    "#808080": ["Gray", "Grey", "Gray (HTML/CSS Gray)", "Trolley Grey"],
    "#808080": ["Gray", "Grey", "Gray (HTML/CSS Gray)", "Trolley Grey"],
    "#808080": ["Gray", "Grey", "Gray (HTML/CSS Gray)", "Trolley Grey"],
    "#bebebe": ["Gray (X11 Gray)"],
    "#8c92ac": ["Cool Grey", "Gray-Blue"],
    "#465945": ["Gray-asparagus"],
    "#00ff00": ["Electric Green", "Green", "Lime (web)"],
    "#1cac78": ["Green (Crayola)"],
    "#008000": ["Ao", "Green (HTML/CSS Color)", "Office Green"],
    "#00a877": ["Green (Munsell)"],
    "#009f6b": ["Green (NCS)"],
    "#66b032": ["Green (RYB)"],
    "#00a550": ["Green (pigment)"],
    "#adff2f": ["Green-yellow"],
    "#a99a86": ["Grullo"],
    "#00ff7f": ["Guppie Green", "Spring Green"],
    "#663854": ["Halayà Úbe"],
    "#446ccf": ["Han Blue"],
    "#5218fa": ["Han Purple"],
    "#e9d66b": ["Arylide Yellow", "Hansa Yellow"],
    "#3fff00": ["Harlequin"],
    "#c90016": ["Harvard Crimson"],
    "#da9100": ["Harvest Gold"],
    "#808000": ["Heart Gold", "Olive"],
    "#df73ff": ["Heliotrope"],
    "#aa98a9": ["Heliotrope Gray", "Rose Quartz"],
    "#f400a1": ["Fashion Fuchsia", "Hollywood Cerise"],
    "#f0fff0": ["Honeydew"],
    "#007fbf": ["Honolulu Blue"],
    "#49796b": ["Hooker's Green"],
    "#ff1dce": ["Hot Magenta"],
    "#ff69b4": ["Hot Pink"],
    "#355e3b": ["Deep Moss Green", "Hunter Green"],
    "#71a6d2": ["Iceberg"],
    "#fcf75e": ["Icterine"],
    "#319177": ["Illuminating Emerald"],
    "#602ffb": ["Imperial"],
    "#002395": ["Imperial Blue"],
    "#66023c": ["Imperial Purple", "Tyrian Purple"],
    "#ed2939": ["Imperial Red", "Red (Pantone)"],
    "#b2ec5d": ["Inchworm"],
    "#4c516d": ["Independence"],
    "#138808": ["India Green"],
    "#cd5c5c": ["Chestnut", "Indian Red"],
    "#e3a857": ["Indian Yellow"],
    "#6f00ff": ["Electric Indigo", "Indigo"],
    "#00416a": ["Dark Imperial Blue", "Indigo (dye)"],
    "#4b0082": ["Indigo (web)"],
    "#091f92": ["Indigo Dye"],
    "#002fa7": ["International Klein Blue"],
    "#ba160c": ["International Orange"],
    "#c0362c": ["International Orange (Golden Gate Bridge)"],
    "#ff4f00": ["International Orange (aerospace)"],
    "#5a4fcf": ["Iris"],
    "#b3446c": ["Irresistible", "Raspberry Rose"],
    "#f4f0ec": ["Isabelline"],
    "#009000": ["Islamic Green"],
    "#b2ffff": ["Celeste", "Italian Sky Blue"],
    "#fffff0": ["Ivory"],
    "#00a86b": ["Jade"],
    "#9d2933": ["Japanese Carmine"],
    "#264348": ["Japanese Indigo"],
    "#5b3256": ["Japanese Violet"],
    "#f8de7e": ["Jasmine", "Mellow Yellow"],
    "#d73b3e": ["Jasper"],
    "#a50b5e": ["Jazzberry Jam"],
    "#da614e": ["Jelly Bean"],
    "#343434": ["Jet"],
    "#fada5e": ["Jonquil", "Naples Yellow", "Royal Yellow", "Stil De Grain Yellow"],
    "#8ab9f1": ["Jordy Blue"],
    "#bdda57": ["June Bud"],
    "#29ab87": ["Jungle Green"],
    "#e8000d": ["KU Crimson"],
    "#4cbb17": ["Kelly Green"],
    "#7c1c05": ["Kenyan Copper"],
    "#3ab09e": ["Keppel"],
    "#c3b091": ["Khaki"],
    "#f0e68c": ["Khaki (X11) (Light Khaki)", "Light Khaki"],
    "#882d17": ["Kobe", "Sienna"],
    "#e79fc4": ["Kobi"],
    "#354230": ["Kombu Green"],
    "#087830": ["La Salle Green"],
    "#d6cadd": ["Languid Lavender"],
    "#26619c": ["Lapis Lazuli"],
    "#fefe22": ["Laser Lemon"],
    "#a9ba9d": ["Laurel Green"],
    "#cf1020": ["Lava"],
    "#e6e6fa": ["Lavender", "Lavender Mist"],
    "#b57edc": ["Lavender (floral)"],
    "#ccccff": ["Lavender Blue", "Periwinkle"],
    "#fff0f5": ["Lavender Blush"],
    "#c4c3d0": ["Lavender Gray"],
    "#9457eb": ["Lavender Indigo", "Navy Purple"],
    "#ee82ee": ["Lavender Magenta", "Violet (web)"],
    "#e6e6fa": ["Lavender", "Lavender Mist"],
    "#fbaed2": ["Lavender Pink"],
    "#967bb6": ["Lavender Purple"],
    "#fba0e3": ["Lavender Rose"],
    "#7cfc00": ["Lawn Green"],
    "#fff700": ["Lemon"],
    "#fffacd": ["Lemon Chiffon"],
    "#cca01d": ["Lemon Curry"],
    "#fdff00": ["Lemon Glacier"],
    "#e3ff00": ["Lemon Lime"],
    "#f6eabe": ["Lemon Meringue"],
    "#fff44f": ["Lemon Yellow"],
    "#545aa7": ["Liberty"],
    "#1a1110": ["Licorice"],
    "#fdd5b1": ["Feldspar", "Light Apricot"],
    "#add8e6": ["Light Blue"],
    "#b5651d": ["Light Brown"],
    "#e66771": ["Light Carmine Pink"],
    "#f08080": ["Light Coral"],
    "#93ccea": ["Light Cornflower Blue"],
    "#f56991": ["Light Crimson"],
    "#e0ffff": ["Light Cyan"],
    "#ff5ccd": ["Light Deep Pink"],
    "#c8ad7f": ["Light French Beige"],
    "#f984ef": ["Light Fuchsia Pink"],
    "#fafad2": ["Light Goldenrod Yellow"],
    "#d3d3d3": ["Light Gray"],
    "#90ee90": ["Light Green"],
    "#ffb3de": ["Light Hot Pink"],
    "#f0e68c": ["Khaki (X11) (Light Khaki)", "Light Khaki"],
    "#d39bcb": ["Light Medium Orchid"],
    "#addfad": ["Light Moss Green", "Moss Green"],
    "#e6a8d7": ["Light Orchid"],
    "#b19cd9": ["Light Pastel Purple"],
    "#ffb6c1": ["Light Pink"],
    "#e97451": ["Burnt Sienna", "Light Red Ochre"],
    "#ffa07a": ["Light Salmon"],
    "#ff9999": ["Light Salmon Pink"],
    "#20b2aa": ["Light Sea Green"],
    "#87cefa": ["Light Sky Blue"],
    "#778899": ["Light Slate Gray"],
    "#b0c4de": ["Light Steel Blue"],
    "#b38b6d": ["Light Taupe"],
    "#e68fac": ["Charm Pink", "Light Thulian Pink"],
    "#ffffe0": ["Light Yellow"],
    "#c8a2c8": ["Lilac"],
    "#bfff00": ["Lime"],
    "#00ff00": ["Electric Green", "Green", "Lime (web)"],
    "#32cd32": ["Lime Green"],
    "#9dc209": ["Limerick"],
    "#195905": ["Lincoln Green"],
    "#faf0e6": ["Linen"],
    "#c19a6b": ["Camel", "Desert", "Fallow", "Lion", "Wood Brown"],
    "#de6fa1": ["China Pink", "Liseran Purple", "Thulian Pink"],
    "#6ca0dc": ["Little Boy Blue"],
    "#534b4f": ["Dark Liver", "Liver"],
    "#b86d29": ["Liver (Dogs)"],
    "#6c2e1f": ["Liver (Organ)"],
    "#987456": ["Liver Chestnut"],
    "#6699cc": ["Blue-gray", "Livid"],
    "#ffe4cd": ["Lumber"],
    "#e62020": ["Lust"],
    "#18453b": ["MSU Green"],
    "#ff00ff": ["Fuchsia", "Magenta"],
    "#ff55a3": ["Brilliant Rose", "Magenta (Crayola)"],
    "#d0417e": ["Magenta (Pantone)"],
    "#ca1f7b": ["Magenta (dye)"],
    "#ff0090": ["Magenta (process)"],
    "#9f4576": ["Magenta Haze"],
    "#aaf0d1": ["Magic Mint"],
    "#f8f4ff": ["Magnolia"],
    "#c04000": ["Mahogany"],
    "#fbec5d": ["Corn", "Maize"],
    "#6050dc": ["Majorelle Blue"],
    "#0bda51": ["Malachite"],
    "#979aaa": ["Manatee"],
    "#ff8243": ["Mango Tango"],
    "#74c365": ["Mantis"],
    "#880085": ["Mardi Gras"],
    "#800000": ["Maroon", "Maroon (HTML/CSS)"],
    "#c32148": ["Bright Maroon", "Maroon (Crayola)"],
    "#800000": ["Maroon", "Maroon (HTML/CSS)"],
    "#b03060": ["Maroon (X11)", "Rich Maroon"],
    "#e0b0ff": ["Mauve"],
    "#915f6d": ["Mauve Taupe", "Raspberry Glace"],
    "#ef98aa": ["Mauvelous"],
    "#4c9141": ["May Green"],
    "#73c2fb": ["Maya Blue"],
    "#e5b73b": ["Meat Brown"],
    "#66ddaa": ["Medium Aquamarine"],
    "#0000cd": ["Medium Blue"],
    "#e2062c": ["Medium Candy Apple Red"],
    "#af4035": ["Medium Carmine", "Pale Carmine"],
    "#f3e5ab": ["Medium Champagne", "Vanilla"],
    "#035096": ["Medium Electric Blue"],
    "#1c352d": ["Medium Jungle Green"],
    "#dda0dd": ["Medium Lavender Magenta", "Pale Plum", "Plum (web)"],
    "#ba55d3": ["Medium Orchid"],
    "#0067a5": ["Medium Persian Blue", "Sapphire Blue"],
    "#9370db": ["Medium Purple"],
    "#bb3385": ["Medium Red-violet"],
    "#aa4069": ["Medium Ruby"],
    "#3cb371": ["Medium Sea Green"],
    "#80daeb": ["Medium Sky Blue"],
    "#7b68ee": ["Medium Slate Blue"],
    "#c9dc87": ["Medium Spring Bud"],
    "#00fa9a": ["Medium Spring Green"],
    "#674c47": ["Medium Taupe"],
    "#48d1cc": ["Medium Turquoise"],
    "#79443b": ["Bole", "Medium Tuscan Red"],
    "#d9603b": ["Medium Vermilion", "Vermilion (Plochere)"],
    "#c71585": ["Medium Violet-red", "Red-violet"],
    "#f8b878": ["Mellow Apricot"],
    "#f8de7e": ["Jasmine", "Mellow Yellow"],
    "#fdbcb4": ["Melon"],
    "#0a7e8c": ["Metallic Seaweed"],
    "#9c7c38": ["Metallic Sunburst"],
    "#e4007c": ["Mexican Pink"],
    "#191970": ["Midnight Blue"],
    "#004953": ["Eagle Green", "Midnight Green"],
    "#e3f988": ["Midori", "Mindaro"],
    "#ffc40c": ["Mikado Yellow"],
    "#e3f988": ["Midori", "Mindaro"],
    "#3eb489": ["Mint"],
    "#f5fffa": ["Mint Cream"],
    "#98ff98": ["Mint Green"],
    "#ffe4e1": ["Misty Rose"],
    "#faebd7": ["Antique White", "Moccasin"],
    "#967117": ["Bistre Brown", "Drab", "Mode Beige", "Sand Dune", "Sandy Taupe"],
    "#73a9c2": ["Moonstone Blue"],
    "#ae0c00": ["Mordant Red 19"],
    "#addfad": ["Light Moss Green", "Moss Green"],
    "#30ba8f": ["Mountain Meadow"],
    "#997a8d": ["Mountbatten Pink"],
    "#306030": ["Mughal Green"],
    "#c54b8c": ["Mulberry"],
    "#ffdb58": ["Mustard"],
    "#21421e": ["Myrtle"],
    "#317873": ["Myrtle Green"],
    "#f6adc6": ["Nadeshiko Pink"],
    "#2a8000": ["Napier Green"],
    "#fada5e": ["Jonquil", "Naples Yellow", "Royal Yellow", "Stil De Grain Yellow"],
    "#ffdead": ["Navajo White"],
    "#000080": ["Navy", "Navy Blue"],
    "#000080": ["Navy", "Navy Blue"],
    "#9457eb": ["Lavender Indigo", "Navy Purple"],
    "#ffa343": ["Neon Carrot"],
    "#fe4164": ["Neon Fuchsia"],
    "#39ff14": ["Neon Green"],
    "#214fc6": ["New Car"],
    "#d7837f": ["New York Pink"],
    "#a4dded": ["Non-photo Blue"],
    "#059033": ["North Texas Green"],
    "#e9ffdb": ["Nyanza"],
    "#990000": ["OU Crimson Red", "Stizza", "USC Cardinal"],
    "#0077be": ["Ocean Boat Blue"],
    "#cc7722": ["Ochre"],
    "#008000": ["Ao", "Green (HTML/CSS Color)", "Office Green"],
    "#43302e": ["Old Burgundy"],
    "#cfb53b": ["Old Gold"],
    "#563c5c": ["English Violet", "Old Heliotrope"],
    "#fdf5e6": ["Old Lace"],
    "#796878": ["Old Lavender"],
    "#673147": ["Old Mauve", "Wine Dregs"],
    "#867e36": ["Old Moss Green"],
    "#c08081": ["Old Rose"],
    "#848482": ["Battleship Grey", "Old Silver"],
    "#808000": ["Heart Gold", "Olive"],
    "#3c341f": ["Olive Drab #7"],
    "#6b8e23": ["Olive Drab (web #3)"],
    "#9ab973": ["Olivine"],
    "#353839": ["Onyx"],
    "#b784a7": ["Opera Mauve"],
    "#ff7f00": ["Orange"],
    "#ff7538": ["Orange (Crayola)"],
    "#ff5800": ["Orange (Pantone)"],
    "#fb9902": ["Orange (RYB)"],
    "#ffa500": ["Orange (Web)"],
    "#ff9f00": ["Orange Peel"],
    "#ff4500": ["Orange-red"],
    "#da70d6": ["Orchid"],
    "#f2bdcd": ["Orchid Pink"],
    "#fb4f14": ["Orioles Orange"],
    "#654321": ["Dark Brown", "Otter Brown"],
    "#414a4c": ["Outer Space"],
    "#ff6e4a": ["Outrageous Orange"],
    "#002147": ["Oxford Blue"],
    "#006600": ["Pakistan Green"],
    "#273be2": ["Palatinate Blue"],
    "#682860": ["Palatinate Purple"],
    "#bcd4e6": ["Beau Blue", "Pale Aqua"],
    "#afeeee": ["Pale Blue", "Pale Turquoise"],
    "#987654": ["Pale Brown"],
    "#af4035": ["Medium Carmine", "Pale Carmine"],
    "#9bc4e2": ["Pale Cerulean"],
    "#ddadaf": ["Pale Chestnut"],
    "#da8a67": ["Copper (Crayola)", "Pale Copper"],
    "#abcdef": ["Pale Cornflower Blue"],
    "#e6be8a": ["Pale Gold"],
    "#eee8aa": ["Pale Goldenrod"],
    "#98fb98": ["Pale Green"],
    "#dcd0ff": ["Pale Lavender"],
    "#f984e5": ["Pale Magenta"],
    "#fadadd": ["Pale Pink"],
    "#dda0dd": ["Medium Lavender Magenta", "Pale Plum", "Plum (web)"],
    "#db7093": ["Pale Red-violet", "Pale Violet-red"],
    "#96ded1": ["Pale Robin Egg Blue"],
    "#c9c0bb": ["Pale Silver"],
    "#ecebbd": ["Pale Spring Bud"],
    "#bc987e": ["Pale Taupe"],
    "#afeeee": ["Pale Blue", "Pale Turquoise"],
    "#db7093": ["Pale Red-violet", "Pale Violet-red"],
    "#78184a": ["Pansy Purple"],
    "#009b7d": ["Paolo Veronese Green"],
    "#ffefd5": ["Papaya Whip"],
    "#e63e62": ["Paradise Pink"],
    "#50c878": ["Emerald", "Paris Green"],
    "#aec6cf": ["Pastel Blue"],
    "#836953": ["Pastel Brown"],
    "#cfcfc4": ["Pastel Gray"],
    "#77dd77": ["Pastel Green"],
    "#f49ac2": ["Pastel Magenta"],
    "#ffb347": ["Pastel Orange"],
    "#dea5a4": ["Pastel Pink"],
    "#b39eb5": ["Pastel Purple"],
    "#ff6961": ["Pastel Red"],
    "#cb99c9": ["Pastel Violet"],
    "#fdfd96": ["Pastel Yellow"],
    "#800080": ["Patriarch", "Purple", "Purple (HTML)"],
    "#536878": ["Dark Electric Blue", "Payne's Grey"],
    "#ffe5b4": ["Peach"],
    "#ffcba4": ["Deep Peach", "Peach (Crayola)"],
    "#ffdab9": ["Peach Puff"],
    "#ffcc99": ["Peach-orange"],
    "#fadfad": ["Peach-yellow"],
    "#d1e231": ["Pear"],
    "#eae0c8": ["Pearl"],
    "#88d8c0": ["Pearl Aqua"],
    "#b768a2": ["Pearly Purple"],
    "#e6e200": ["Peridot"],
    "#ccccff": ["Lavender Blue", "Periwinkle"],
    "#1c39bb": ["Persian Blue"],
    "#00a693": ["Persian Green"],
    "#32127a": ["Persian Indigo"],
    "#d99058": ["Persian Orange"],
    "#f77fbe": ["Persian Pink"],
    "#701c1c": ["Persian Plum", "Prune"],
    "#cc3333": ["Persian Red"],
    "#fe28a2": ["Persian Rose"],
    "#ec5800": ["Persimmon"],
    "#cd853f": ["Peru"],
    "#df00ff": ["Phlox", "Psychedelic Purple"],
    "#000f89": ["Phthalo Blue"],
    "#123524": ["Phthalo Green"],
    "#45b1e8": ["Picton Blue"],
    "#c30b4e": ["Pictorial Carmine"],
    "#fddde6": ["Piggy Pink"],
    "#01796f": ["Pine Green"],
    "#ffc0cb": ["Pink"],
    "#d74894": ["Pink (Pantone)"],
    "#ffddf4": ["Pink Lace"],
    "#d8b2d1": ["Pink Lavender"],
    "#e7accf": ["Pink Pearl"],
    "#f78fa7": ["Pink Sherbet"],
    "#ff9966": ["Atomic Tangerine", "Pink-orange"],
    "#93c572": ["Pistachio"],
    "#e5e4e2": ["Platinum"],
    "#8e4585": ["Plum"],
    "#dda0dd": ["Medium Lavender Magenta", "Pale Plum", "Plum (web)"],
    "#86608e": ["French Lilac", "Pomp And Power"],
    "#be4f62": ["Popstar"],
    "#ff5a36": ["Portland Orange"],
    "#b0e0e6": ["Powder Blue", "Powder Blue (web)"],
    "#b0e0e6": ["Powder Blue", "Powder Blue (web)"],
    "#ff8f00": ["Princeton Orange"],
    "#701c1c": ["Persian Plum", "Prune"],
    "#003153": ["Prussian Blue"],
    "#df00ff": ["Phlox", "Psychedelic Purple"],
    "#cc8899": ["Puce"],
    "#722f37": ["Puce Red", "Wine"],
    "#644117": ["Pullman Brown (UPS Brown)"],
    "#ff7518": ["Pumpkin"],
    "#800080": ["Patriarch", "Purple", "Purple (HTML)"],
    "#800080": ["Patriarch", "Purple", "Purple (HTML)"],
    "#9f00c5": ["Purple (Munsell)"],
    "#a020f0": ["Purple (X11)", "Veronica"],
    "#69359c": ["Purple Heart"],
    "#9678b6": ["Purple Mountain Majesty"],
    "#4e5180": ["Purple Navy"],
    "#fe4eda": ["Purple Pizzazz"],
    "#50404d": ["Purple Taupe"],
    "#9a4eae": ["Purpureus"],
    "#51484f": ["Quartz"],
    "#436b95": ["Queen Blue"],
    "#e8cc07": ["Queen Pink"],
    "#8e3a59": ["Quinacridone Magenta"],
    "#5d8aa8": ["Air Force Blue (RAF)", "Rackley"],
    "#ff355e": ["Radical Red"],
    "#fbab60": ["Rajah"],
    "#e30b5d": ["Raspberry"],
    "#915f6d": ["Mauve Taupe", "Raspberry Glace"],
    "#e25098": ["Raspberry Pink"],
    "#b3446c": ["Irresistible", "Raspberry Rose"],
    "#826644": ["Raw Umber"],
    "#ff33cc": ["Razzle Dazzle Rose"],
    "#e3256b": ["Razzmatazz"],
    "#8d4e85": ["Razzmic Berry"],
    "#ff0000": ["Red"],
    "#ee204d": ["Red (Crayola)"],
    "#f2003c": ["Red (Munsell)"],
    "#c40233": ["Red (NCS)"],
    "#ed2939": ["Imperial Red", "Red (Pantone)"],
    "#fe2712": ["Red (RYB)"],
    "#ed1c24": ["Red (pigment)"],
    "#860111": ["Red Devil"],
    "#e40078": ["Red-Purple"],
    "#a52a2a": ["Auburn", "Brown (web)", "Red-brown"],
    "#ff5349": ["Red-orange"],
    "#c71585": ["Medium Violet-red", "Red-violet"],
    "#ab4e52": ["Redwood", "Rose Vale"],
    "#522d80": ["Regalia"],
    "#002387": ["Resolution Blue"],
    "#777696": ["Rhythm"],
    "#004040": ["Rich Black"],
    "#f1a7fe": ["Rich Brilliant Lavender"],
    "#d70040": ["Carmine (M&P)", "Rich Carmine"],
    "#0892d0": ["Rich Electric Blue"],
    "#a76bcf": ["Rich Lavender"],
    "#b666d2": ["Rich Lilac"],
    "#b03060": ["Maroon (X11)", "Rich Maroon"],
    "#414833": ["Rifle Green"],
    "#704241": ["Deep Coffee", "Roast Coffee"],
    "#00cccc": ["Robin Egg Blue"],
    "#8a7f80": ["Rocket Metallic"],
    "#838996": ["Roman Silver"],
    "#ff007f": ["Bright Pink", "Rose"],
    "#f9429e": ["Rose Bonbon"],
    "#674846": ["Rose Ebony"],
    "#b76e79": ["Rose Gold"],
    "#e32636": ["Alizarin Crimson", "Rose Madder"],
    "#ff66cc": ["Rose Pink"],
    "#aa98a9": ["Heliotrope Gray", "Rose Quartz"],
    "#c21e56": ["Rose Red"],
    "#905d5d": ["Rose Taupe"],
    "#ab4e52": ["Redwood", "Rose Vale"],
    "#65000b": ["Rosewood"],
    "#d40000": ["Rosso Corsa"],
    "#bc8f8f": ["Rosy Brown"],
    "#0038a8": ["Royal Azure"],
    "#002366": ["Royal Blue"],
    "#4169e1": ["Royal Blue (web)"],
    "#ca2c92": ["Royal Fuchsia"],
    "#7851a9": ["Royal Purple"],
    "#fada5e": ["Jonquil", "Naples Yellow", "Royal Yellow", "Stil De Grain Yellow"],
    "#ce4676": ["Ruber"],
    "#d10056": ["Rubine Red"],
    "#e0115f": ["Ruby"],
    "#9b111e": ["Ruby Red"],
    "#ff0028": ["Ruddy"],
    "#bb6528": ["Ruddy Brown"],
    "#e18e96": ["Ruddy Pink"],
    "#a81c07": ["Rufous"],
    "#80461b": ["Russet"],
    "#679267": ["Russian Green"],
    "#32174d": ["Russian Violet"],
    "#b7410e": ["Rust"],
    "#da2c43": ["Rusty Red"],
    "#ff7e00": ["Amber (SAE/ECE)", "SAE/ECE Amber (Color)"],
    "#00563f": ["Castleton Green", "Sacramento State Green"],
    "#8b4513": ["Saddle Brown"],
    "#ff6700": ["Safety Orange (blaze Orange)"],
    "#eed202": ["Safety Yellow"],
    "#f4c430": ["Saffron"],
    "#bcb88a": ["Sage"],
    "#ff8c69": ["Salmon"],
    "#ff91a4": ["Salmon Pink"],
    "#c2b280": ["Ecru", "Sand"],
    "#967117": ["Bistre Brown", "Drab", "Mode Beige", "Sand Dune", "Sandy Taupe"],
    "#ecd540": ["Sandstorm"],
    "#f4a460": ["Sandy Brown"],
    "#967117": ["Bistre Brown", "Drab", "Mode Beige", "Sand Dune", "Sandy Taupe"],
    "#92000a": ["Sangria"],
    "#507d2a": ["Sap Green"],
    "#0f52ba": ["Sapphire"],
    "#0067a5": ["Medium Persian Blue", "Sapphire Blue"],
    "#cba135": ["Satin Sheen Gold"],
    "#ff2400": ["Scarlet"],
    "#fd0e35": ["Scarlet (Crayola)", "Tractor Red"],
    "#ff91af": ["Baker-Miller Pink", "Schauss Pink"],
    "#ffd800": ["School Bus Yellow"],
    "#76ff7a": ["Screamin' Green"],
    "#006994": ["Sea Blue"],
    "#2e8b57": ["Sea Green"],
    "#321414": ["Seal Brown"],
    "#fff5ee": ["Seashell"],
    "#ffba00": ["Selective Yellow"],
    "#704214": ["Sepia"],
    "#8a795d": ["Shadow"],
    "#778ba5": ["Shadow Blue"],
    "#ffcff1": ["Shampoo"],
    "#009e60": ["Shamrock Green"],
    "#8fd400": ["Sheen Green"],
    "#d98695": ["Shimmering Blush"],
    "#fc0fc0": ["Shocking Pink"],
    "#ff6fff": ["Shocking Pink (Crayola)", "Ultra Pink"],
    "#882d17": ["Kobe", "Sienna"],
    "#c0c0c0": ["Silver"],
    "#acacac": ["Silver Chalice"],
    "#5d89ba": ["Silver Lake Blue"],
    "#c4aead": ["Silver Pink"],
    "#bfc1c2": ["Silver Sand"],
    "#cb410b": ["Sinopia"],
    "#007474": ["Skobeloff"],
    "#87ceeb": ["Sky Blue"],
    "#cf71af": ["Sky Magenta"],
    "#6a5acd": ["Slate Blue"],
    "#708090": ["Slate Gray"],
    "#003399": ["Dark Powder Blue", "Smalt"],
    "#c84186": ["Smitten"],
    "#738276": ["Smoke"],
    "#933d41": ["Smokey Topaz"],
    "#100c08": ["Smoky Black"],
    "#fffafa": ["Snow"],
    "#cec8ef": ["Soap"],
    "#893843": ["Solid Pink"],
    "#757575": ["Sonic Silver"],
    "#1d2951": ["Space Cadet"],
    "#807532": ["Spanish Bistre"],
    "#0070b8": ["Spanish Blue"],
    "#d10047": ["Spanish Carmine"],
    "#e51a4c": ["Spanish Crimson"],
    "#989898": ["Spanish Gray"],
    "#009150": ["Spanish Green"],
    "#e86100": ["Spanish Orange"],
    "#f7bfbe": ["Spanish Pink"],
    "#e60026": ["Spanish Red"],
    "#00ffff": ["Aqua", "Cyan", "Electric Cyan", "Spanish Sky Blue"],
    "#4c2882": ["Spanish Violet"],
    "#007f5c": ["Spanish Viridian"],
    "#9e1316": ["Spartan Crimson"],
    "#0fc0fc": ["Spiro Disco Ball"],
    "#a7fc00": ["Spring Bud"],
    "#00ff7f": ["Guppie Green", "Spring Green"],
    "#23297a": ["St. Patrick's Blue"],
    "#007bbb": ["Star Command Blue"],
    "#4682b4": ["Steel Blue"],
    "#cc33cc": ["Steel Pink"],
    "#fada5e": ["Jonquil", "Naples Yellow", "Royal Yellow", "Stil De Grain Yellow"],
    "#990000": ["OU Crimson Red", "Stizza", "USC Cardinal"],
    "#4f666a": ["Stormcloud"],
    "#e4d96f": ["Straw"],
    "#fc5a8d": ["Strawberry"],
    "#ffcc33": ["Sunglow"],
    "#e3ab57": ["Sunray"],
    "#fad6a5": ["Deep Champagne", "Sunset", "Tuscan"],
    "#fd5e53": ["Sunset Orange"],
    "#cf6ba9": ["Super Pink"],
    "#d2b48c": ["Tan"],
    "#f94d00": ["Tangelo"],
    "#f28500": ["Tangerine"],
    "#ffcc00": ["Tangerine Yellow", "USC Gold"],
    "#e4717a": ["Candy Pink", "Tango Pink"],
    "#483c32": ["Dark Lava", "Dark Taupe", "Taupe"],
    "#8b8589": ["Taupe Gray"],
    "#cd5700": ["Tawny", "Tenné"],
    "#d0f0c0": ["Tea Green"],
    "#f4c2c2": ["Baby Pink", "Tea Rose"],
    "#f88379": ["Congo Pink", "Coral Pink", "Tea Rose (orange)"],
    "#008080": ["Teal", "Windows 95/98 Desktop"],
    "#367588": ["Teal Blue"],
    "#99e6b3": ["Teal Deer"],
    "#00827f": ["Teal Green"],
    "#cf3476": ["Telemagenta"],
    "#cd5700": ["Tawny", "Tenné"],
    "#e2725b": ["Terra Cotta"],
    "#d8bfd8": ["Thistle"],
    "#de6fa1": ["China Pink", "Liseran Purple", "Thulian Pink"],
    "#fc89ac": ["Tickle Me Pink"],
    "#0abab5": ["Tiffany Blue"],
    "#e08d3c": ["Tiger's Eye"],
    "#dbd7d2": ["Timberwolf"],
    "#eee600": ["Titanium Yellow"],
    "#ff6347": ["Tomato"],
    "#746cc0": ["Toolbox"],
    "#ffc87c": ["Topaz"],
    "#fd0e35": ["Scarlet (Crayola)", "Tractor Red"],
    "#808080": ["Gray", "Grey", "Gray (HTML/CSS Gray)", "Trolley Grey"],
    "#00755e": ["Tropical Rain Forest"],
    "#0073cf": ["True Blue"],
    "#417dc1": ["Tufts Blue"],
    "#ff878d": ["Tulip"],
    "#deaa88": ["Tumbleweed"],
    "#b57281": ["Turkish Rose"],
    "#30d5c8": ["Turquoise"],
    "#00ffef": ["Turquoise Blue"],
    "#a0d6b4": ["Turquoise Green"],
    "#fad6a5": ["Deep Champagne", "Sunset", "Tuscan"],
    "#6f4e37": ["Coffee", "Tuscan Brown"],
    "#7c4848": ["Tuscan Red"],
    "#a67b5b": ["Café Au Lait", "French Beige", "Tuscan Tan"],
    "#c09999": ["Tuscany"],
    "#4099ff": ["Tweeter blue"],
    "#8a496b": ["Twilight Lavender"],
    "#66023c": ["Imperial Purple", "Tyrian Purple"],
    "#0033aa": ["UA Blue"],
    "#d9004c": ["UA Red"],
    "#536895": ["UCLA Blue"],
    "#ffb300": ["UCLA Gold"],
    "#3cd070": ["UFO Green"],
    "#014421": ["Forest Green", "UP Forest Green"],
    "#7b1113": ["UP Maroon"],
    "#004f98": ["USAFA Blue"],
    "#990000": ["OU Crimson Red", "Stizza", "USC Cardinal"],
    "#ffcc00": ["Tangerine Yellow", "USC Gold"],
    "#8878c3": ["Ube"],
    "#ff6fff": ["Shocking Pink (Crayola)", "Ultra Pink"],
    "#fc6c85": ["Ultra Red", "Wild Watermelon"],
    "#120a8f": ["Ultramarine"],
    "#4166f5": ["Ultramarine Blue"],
    "#635147": ["Umber"],
    "#ffddca": ["Unbleached Silk"],
    "#5b92e5": ["United Nations Blue"],
    "#b78727": ["University Of California Gold"],
    "#f77f00": ["University Of Tennessee Orange"],
    "#ffff66": ["Unmellow Yellow"],
    "#ae2029": ["Upsdell Red"],
    "#e1ad21": ["Urobilin"],
    "#d3003f": ["Utah Crimson"],
    "#f3e5ab": ["Medium Champagne", "Vanilla"],
    "#f38fa9": ["Vanilla Ice"],
    "#c5b358": ["Vegas Gold"],
    "#c80815": ["Venetian Red"],
    "#43b3ae": ["Verdigris"],
    "#e34234": ["Cinnabar", "Vermilion"],
    "#d9603b": ["Medium Vermilion", "Vermilion (Plochere)"],
    "#a020f0": ["Purple (X11)", "Veronica"],
    "#8f00ff": ["Electric Violet", "Violet"],
    "#8601af": ["Violet (RYB)"],
    "#7f00ff": ["Violet (color Wheel)"],
    "#ee82ee": ["Lavender Magenta", "Violet (web)"],
    "#324ab2": ["Violet-blue"],
    "#f75394": ["Violet-red"],
    "#40826d": ["Viridian"],
    "#009698": ["Viridian Green"],
    "#922724": ["Vivid Auburn"],
    "#9f1d35": ["Vivid Burgundy"],
    "#da1d81": ["Vivid Cerise"],
    "#cc00ff": ["Vivid Orchid"],
    "#00ccff": ["Vivid Sky Blue"],
    "#ffa089": ["Vivid Tangerine"],
    "#9f00ff": ["Vivid Violet"],
    "#004242": ["Warm Black"],
    "#a4f4f9": ["Waterspout"],
    "#645452": ["Wenge"],
    "#f5deb3": ["Wheat"],
    "#ffffff": ["White"],
    "#f5f5f5": ["White Smoke"],
    "#a2add0": ["Wild Blue Yonder"],
    "#d470a2": ["Wild Orchid"],
    "#ff43a4": ["Wild Strawberry"],
    "#fc6c85": ["Ultra Red", "Wild Watermelon"],
    "#fd5800": ["Willpower Orange"],
    "#00adef": ["Windows 8 logo"],
    "#008080": ["Teal", "Windows 95/98 Desktop"],
    "#004e98": ["Windows XP Desktop"],
    "#ae6838": ["Windsor Tan"],
    "#722f37": ["Puce Red", "Wine"],
    "#673147": ["Old Mauve", "Wine Dregs"],
    "#c9a0dc": ["Wisteria"],
    "#c19a6b": ["Camel", "Desert", "Fallow", "Lion", "Wood Brown"],
    "#738678": ["Xanadu"],
    "#0f4d92": ["Yale Blue"],
    "#1c2841": ["Yankees Blue"],
    "#ffff00": ["Electric Yellow", "Yellow"],
    "#fce883": ["Yellow (Crayola)"],
    "#efcc00": ["Yellow (Munsell)"],
    "#ffd300": ["Cyber Yellow", "Yellow (NCS)"],
    "#fedf00": ["Yellow (Pantone)"],
    "#fefe33": ["Yellow (RYB)"],
    "#ffef00": ["Canary Yellow", "Yellow (process)"],
    "#ffae42": ["Yellow Orange"],
    "#fff000": ["Yellow Rose"],
    "#9acd32": ["Yellow-green"],
    "#0014a8": ["Zaffre"],
    "#2c1608": ["Zinnwaldite Brown"],
    "#39a78e": ["Zomp"]
}
